name: Publish Sphinx Documentation

on:
  release:
    types: [published]

jobs:
  publish_sphinx_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -e .
          pip install sphinx furo sphinx_multiversion
      - name: Sphinx build
        run: |
          sphinx-multiversion docs docs/_build/html
      - name: Create index.html
        run: |
          cp docs/_templates/gh-pages-redirect.html docs/_build/html/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
